### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by d3rped** [danielfullmer/nixos-config#1]
I'd like to add (and or adapt) parts of your configuration to my [repo](https://git.ophanim.de/derped/nixos/src/branch/master).
Could you please add a LICENSE file to your repo?

Also on a side note:
I own a Surface Pro (2017)
When I'm using linux 5.x the applications chromium and anki randomly stop responding. (ignores SIGTERM and there is no relevant output on STDERR or the journal)
I'd just like to know if you are experiencing similar issues on your Pro 4.

Thanks a lot.

**Comment by danielfullmer** [comment]
Sure. I just added the MIT license. Hope some stuff in here is useful!

I actually haven't tested the most recent commit updating to 5.x on the SP4--other than making sure it compiles. I'll give it a try either later today or tomorrow and I'll let you know if I have the same problem.

It's on my TODO list to convert the surfacepro4.nix file to a nixos module which would support other devices, but I haven't had a pressing reason to or the ability to test.

**Comment by danielfullmer** [comment]
Just tested with the current version in this repo. Seems to be working fine for me.  If needed, you can use the "4.19.37-1" tag from the jakeday repo, which seems current as well.
